In [ ]:
import pandas as pd
data={"Department":["HR","Sales","IT","Sales","IT","HR","Sales"],
      "Employee":["A","B","C","D","E","F","G"],
      "Salary":[50000,60000,45000,48000,70000,72000,71000],
      "Experience":[2,4,3,5,6,7,5]}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [ ]:
df3=df.groupby("Experience").sum()
print(df3)

            Department Employee  Salary
Experience
2                   HR        A   50000
3                   IT        C   45000
4                Sales        B   60000
5           SalesSales       DG  119000
6                   IT        E   70000
7                   HR        F   72000

In [ ]:
# agregation function
dfa=df.groupby("Department")["Salary"].sum()
print(dfa)
df3=df.groupby("Experience")["Salary"].sum()
print(df3)

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64
Experience
2     50000
3     45000
4     60000
5    119000
6     70000
7     72000
Name: Salary, dtype: int64

In [ ]:
df1=df.groupby(["Experience","Department"]).sum()
dfq=df.groupby("Department").sum()
dfw=df.groupby(["Department","Experience"]).sum()
print(dfw)
print(dfq)
print(df1)

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000
           Employee  Salary  Experience
Department
HR               AF  122000           9
IT               CE  115000           9
Sales           BDG  179000          14
                      Employee  Salary
Experience Department
2          HR                A   50000
3          IT                C   45000
4          Sales             B   60000
5          Sales            DG  119000
6          IT                E   70000
7          HR                F   72000

In [25]:
# Custom aggregation
s=df.groupby("Department").agg({"Salary":"sum","Experience":"mean"})
s["Experience"] = s["Experience"].round(2)
print(s)

            Salary  Experience
Department
HR          122000        4.50
IT          115000        4.50
Sales       179000        4.67

In [27]:
df.groupby("Department")["Salary"].agg(["sum","mean","std"])

               sum          mean           std
Department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
Sales       179000  59666.666667  11503.622618

In [35]:
s=df.groupby("Department")["Salary"].agg(["sum","mean","std"])
s["sum"]=s["sum"].round(2)
s["mean"]=s["mean"].round(2)
s["std"]=s["std"].round(2)
print(s)

               sum      mean       std
Department
HR          122000  61000.00  15556.35
IT          115000  57500.00  17677.67
Sales       179000  59666.67  11503.62

In [43]:
# broadcasting group mean to each row
df9=df.groupby("Department")["Salary"].transform("mean")
print(df9)
df["Dept_avg_salary"]=df9
print(df)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Salary, dtype: float64
  Department Employee  Salary  Experience  Dept_avg_salary  dept_avg_salary
0         HR        A   50000           2     61000.000000     61000.000000
1      Sales        B   60000           4     59666.666667     59666.666667
2         IT        C   45000           3     57500.000000     57500.000000
3      Sales        D   48000           5     59666.666667     59666.666667
4         IT        E   70000           6     57500.000000     57500.000000
5         HR        F   72000           7     61000.000000     61000.000000
6      Sales        G   71000           5     59666.666667     59666.666667

In [38]:
# broadcasting group mean to each row
df["Dept_avg_salary"]=df.groupby("Department")["Salary"].transform("mean")
print(df)

  Department Employee  Salary  Experience  Dept_avg_salary
0         HR        A   50000           2     61000.000000
1      Sales        B   60000           4     59666.666667
2         IT        C   45000           3     57500.000000
3      Sales        D   48000           5     59666.666667
4         IT        E   70000           6     57500.000000
5         HR        F   72000           7     61000.000000
6      Sales        G   71000           5     59666.666667

In [42]:
# filtering groups
df5=df.groupby("Department").filter(lambda x:len(x)>2)
print(df5)

  Department Employee  Salary  Experience  Dept_avg_salary  dept_avg_salary
1      Sales        B   60000           4     59666.666667     59666.666667
3      Sales        D   48000           5     59666.666667     59666.666667
6      Sales        G   71000           5     59666.666667     59666.666667

In [44]:
# pivot table
df.pivot_table(values="Salary",index="Department",columns="Experience",aggfunc="mean")

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [48]:
# pivot table
df.pivot_table(values="Experience",index="Department",aggfunc="sum")

            Experience
Department
HR                   9
IT                   9
Sales               14

In [56]:
# agricultural data example
raw_data={"Season":["Kharif","Rabi","Rabi","Summer","Kharif","Rabi","Summer","Summer"],
          "Crops":["Rice","Wheat","Blackgram","Sugarcane","Maize","Mustard","Tomato","Chilli"],
          "Area(in ac)":[3,2,1.5,1,3.1,2,2.1,2],
          "Yield(in q)":[40,30,10,60,35,12,50,50]}
df=pd.DataFrame(raw_data)
print(df)

   Season      Crops  Area(in ac)  Yield(in q)
0  Kharif       Rice          3.0           40
1    Rabi      Wheat          2.0           30
2    Rabi  Blackgram          1.5           10
3  Summer  Sugarcane          1.0           60
4  Kharif      Maize          3.1           35
5    Rabi    Mustard          2.0           12
6  Summer     Tomato          2.1           50
7  Summer     Chilli          2.0           50

In [57]:
df.groupby(["Season","Crops"]).sum()

                  Area(in ac)  Yield(in q)
Season Crops
Kharif Maize              3.1           35
       Rice               3.0           40
Rabi   Blackgram          1.5           10
       Mustard            2.0           12
       Wheat              2.0           30
Summer Chilli             2.0           50
       Sugarcane          1.0           60
       Tomato             2.1           50

In [60]:
df.groupby("Season")["Yield(in q)"].sum()

Season
Kharif     75
Rabi       52
Summer    160
Name: Yield(in q), dtype: int64

In [62]:
df.groupby("Crops").agg({"Area(in ac)":"sum","Yield(in q)":"mean"})

           Area(in ac)  Yield(in q)
Crops
Blackgram          1.5         10.0
Chilli             2.0         50.0
Maize              3.1         35.0
Mustard            2.0         12.0
Rice               3.0         40.0
Sugarcane          1.0         60.0
Tomato             2.1         50.0
Wheat              2.0         30.0

In [63]:
df.groupby("Season").agg({"Area(in ac)":"sum","Yield(in q)":"mean"})

        Area(in ac)  Yield(in q)
Season
Kharif          6.1    37.500000
Rabi            5.5    17.333333
Summer          5.1    53.333333

In [66]:
# broadcasting
avg=df["Average yields"]=df.groupby("Season")["Yield(in q)"].transform("mean")
print(avg)
print(df)

0    37.500000
1    17.333333
2    17.333333
3    53.333333
4    37.500000
5    17.333333
6    53.333333
7    53.333333
Name: Yield(in q), dtype: float64
   Season      Crops  Area(in ac)  Yield(in q)  Average yields
0  Kharif       Rice          3.0           40       37.500000
1    Rabi      Wheat          2.0           30       17.333333
2    Rabi  Blackgram          1.5           10       17.333333
3  Summer  Sugarcane          1.0           60       53.333333
4  Kharif      Maize          3.1           35       37.500000
5    Rabi    Mustard          2.0           12       17.333333
6  Summer     Tomato          2.1           50       53.333333
7  Summer     Chilli          2.0           50       53.333333

In [72]:
df.groupby("Season").filter(lambda x:len(x)>=2)

   Season      Crops  Area(in ac)  Yield(in q)  Average yields
0  Kharif       Rice          3.0           40       37.500000
1    Rabi      Wheat          2.0           30       17.333333
2    Rabi  Blackgram          1.5           10       17.333333
3  Summer  Sugarcane          1.0           60       53.333333
4  Kharif      Maize          3.1           35       37.500000
5    Rabi    Mustard          2.0           12       17.333333
6  Summer     Tomato          2.1           50       53.333333
7  Summer     Chilli          2.0           50       53.333333